name: Daily Birthday Wish

on:
  schedule:
    - cron: '0 8 * * *'  # Runs every day at 8 AM UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11 (Zulu)
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'zulu'  # Use Zulu OpenJDK distribution

      - name: Compile and run the program
        run: |
          # Create the bin directory for compiled classes
          mkdir -p bin

          # Compile the Java files and include JAR files in the classpath
          javac -d bin -cp "libs/*" src/com/rocco/birthdays/WishBirthdays.java

          # Run the Java program, including JAR files in the classpath
          java -cp "bin:libs/*" com.rocco.birthdays.WishBirthdays
