name: Daily Birthday Wish

on:
  schedule:
    - cron: '0 8 * * *'  # Runs every day at 8 AM UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'openjdk'  # Use OpenJDK distribution

      - name: Compile and run the program
        run: |
          mkdir -p bin
          javac -d bin src/com/rocco/birthdays/WishBirthdays.java
          java -cp bin com.rocco.birthdays.WishBirthdays
